# Generated by Django 5.2.7 on 2026-01-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0011_tbl_patient_current_trimester'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_district',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('reschedule_date', models.DateField(blank=True, null=True)),
                ('reschedule_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_doctor')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_patient')),
            ],
        ),
    ]
