# Generated by Django 5.2.7 on 2026-01-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_tbl_patient_current_trimester'),
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_district',
            new_name='tbl_appointment',
        ),
    ]
