# Generated by Django 5.2.7 on 2026-01-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_rename_tbl_district_tbl_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_appointment',
            name='admin_note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
