# Generated by Django 5.2.7 on 2025-12-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_tbl_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_doctor',
            name='login_id',
        ),
    ]
