# Generated by Django 5.2.7 on 2025-12-11 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_tbl_doctor_login_id'),
        ('guestapp', '0003_delete_tbl_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login'),
        ),
    ]
