# Generated by Django 5.2.7 on 2025-12-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_doctor_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
