# Generated by Django 5.2.7 on 2025-12-12 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_tbl_doctor_image'),
        ('guestapp', '0003_delete_tbl_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=10)),
                ('last_cycle_date', models.DateField()),
                ('current_trimester', models.IntegerField(null=True, blank=True)),
                ('edd_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('profile_lock_status', models.CharField(default='unlocked', max_length=20)),
                ('lock_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_doctor')),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login')),
            ],
        ),
    ]
