# Generated by Django 5.2.7 on 2025-12-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_tbl_patient_current_trimester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_patient',
            name='current_trimester',
        ),
    ]
