# Generated by Django 5.2.7 on 2025-12-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_remove_tbl_patient_current_trimester'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_patient',
            name='current_trimester',
            field=models.IntegerField(default=1),
        ),
    ]
