# Generated by Django 5.2.7 on 2026-01-07 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_tbl_patient_current_trimester'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_doctor')),
            ],
        ),
    ]
