# Generated by Django 5.2.7 on 2026-01-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_tbl_doctor_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
