# Generated by Django 5.2.7 on 2026-01-13 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_tbl_doctor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_medical_record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(choices=[('Patient', 'Patient'), ('Admin', 'Admin')], max_length=20)),
                ('patient_uploaded_file', models.FileField(blank=True, null=True, upload_to='medical_records/patient/')),
                ('admin_uploaded_file', models.FileField(blank=True, null=True, upload_to='medical_records/admin/')),
                ('doctor_view_status', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='adminapp.tbl_patient')),
            ],
            options={
                'db_table': 'tbl_medical_record',
                'ordering': ['-record_date'],
            },
        ),
    ]
