# Generated by Django 5.2.7 on 2026-01-13 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_tbl_medical_record'),
        ('patientapp', '0003_tbl_appointment_admin_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.TextField()),
                ('medicines', models.TextField(help_text='Medicine name, dosage, duration')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('prescription_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patientapp.tbl_appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_patient')),
            ],
            options={
                'db_table': 'tbl_prescription',
            },
        ),
    ]
