# Generated by Django 5.2.7 on 2026-01-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_tbl_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_medical_record',
            name='doctor_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
