# Generated by Django 5.2.7 on 2026-01-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_tbl_medical_record_doctor_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_prescription',
            name='dosage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
