# Generated by Django 5.2.7 on 2026-03-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_simplify_tbl_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_patient',
            name='emergency_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_patient',
            name='miscarriage_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_patient',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_patient',
            name='transfer_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_patient',
            name='transfer_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Delivered', 'Delivered'), ('Miscarriage', 'Miscarriage'), ('Emergency', 'Emergency'), ('Transferred', 'Transferred')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_payment',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], max_length=20),
        ),
    ]
