# Generated by Django 5.2.7 on 2025-12-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0007_tbl_patient'),
        ('guestapp', '0003_delete_tbl_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_trimester_update',
            fields=[
                ('trimester_id', models.AutoField(primary_key=True, serialize=False)),
                ('trimester_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_doctor')),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_patient')),
            ],
        ),
    ]
