# Generated by Django 5.2.7 on 2026-01-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_tbl_prescription'),
        ('doctorapp', '0001_initial'),
        ('patientapp', '0003_tbl_appointment_admin_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_visit_history',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('details', models.TextField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('health_status', models.CharField(max_length=50)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.tbl_appointment')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_patient')),
            ],
        ),
    ]
