# Generated by Django 5.2.7 on 2026-01-22 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_tbl_prescription_dosage'),
        ('doctorapp', '0002_tbl_visit_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_delivery_details',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('Normal', 'Normal Delivery'), ('C-Section', 'C-Section'), ('Assisted', 'Assisted Delivery')], max_length=20)),
                ('baby_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=4)),
                ('baby_condition', models.CharField(choices=[('Good', 'Good'), ('Stable', 'Stable'), ('Critical', 'Critical')], max_length=20)),
                ('mother_condition', models.CharField(choices=[('Good', 'Good'), ('Stable', 'Stable'), ('Critical', 'Critical')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='adminapp.tbl_doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='adminapp.tbl_patient')),
            ],
            options={
                'db_table': 'tbl_delivery_details',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
