# Generated by Django 5.2.7 on 2025-12-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0002_tbl_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_doctor',
        ),
    ]
